services:
  - type: web
    name: django-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn lux.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    plan: free
    envVars:
      - key: DJANGO_SECRET_KEY
        value: "your-secret-key"
      - key: DB_NAME
        value: "mydatabase_in8a"
      - key: DB_USER
        value: "jeff"
      - key: DB_PASSWORD
        value: "Xin0IadqgJoIoHa08bWBsj2yUASLlI3c"
      - key: DB_HOST
        value: "dpg-cv2tju3qf0us7381pj10-a"
      - key: DB_PORT
        value: "5432"
