name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: jeff
          POSTGRES_PASSWORD: Xin0IadqgJoIoHa08bWBsj2yUASLlI3c
          POSTGRES_DB: mydatabase_in8a
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-django flake8

      - name: Run migrations
        env:
          DATABASE_URL: postgresql://jeff:Xin0IadqgJoIoHa08bWBsj2yUASLlI3c@dpg-cv2tju3qf0us7381pj10-a.oregon-postgres.render.com/mydatabase_in8a
        run: |
          python manage.py migrate

      - name: Run tests
        env:
          DATABASE_URL: postgresql://jeff:Xin0IadqgJoIoHa08bWBsj2yUASLlI3c@dpg-cv2tju3qf0us7381pj10-a.oregon-postgres.render.com/mydatabase_in8a
        run: |
          pytest

      - name: Run flake8 (Linting)
        run: |
          flake8 .
